# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3f322b6923038db1c79a58fb917d5f80848faec8ec45651a5e898e898bb99c4fea1156a4943fbcc99b88955da622ffb157b6441291e7f48a1095eb6e21eb49da

test:
  secret_key_base: 3c6d85be17174c39040ff829a0d8e57cb63038128c9d2dc67b756389f8a34ece0831defc98a14aaf124530f707ae4d3e6003d77a5f9a6a6d513e8cab1fbc5542

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
